spring.application.name=phd-progress
spring.datasource.url=jdbc:postgresql://localhost:5432/phd_progress
spring.datasource.username=postgres
spring.datasource.password=Pradeep@184

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect